export interface Aps {
  _id: ObjectId;
  city: string;
  company: string;
  country: string;
  flag: string;
  name: string;
  ns: string;
  parkingSpaces: number;
}

export const aps: Aps[] = [
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Africa Avenue",
    ns: "aa",
    parkingSpaces: "286",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Agami",
    ns: "agami",
    parkingSpaces: "110",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Alumim",
    ns: "alumim",
    parkingSpaces: "36",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Aminadav 16",
    ns: "aminadav16",
    parkingSpaces: "54",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Aminadav 18, 20",
    ns: "aminadav1820",
    parkingSpaces: "96",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Amore Edge",
    ns: "amore",
    parkingSpaces: "106",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Bank of India",
    ns: "boi",
    parkingSpaces: "225",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Bugrashov",
    ns: "bugrashov",
    parkingSpaces: "229",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Chandan Society",
    ns: "chandan",
    parkingSpaces: "105",
  },
  {
    city: "Lugano",
    company: "Elecon",
    country: "Switzerland",
    flag: "🇨🇭",
    name: "P.zzo Chiattone",
    ns: "chiattone",
    parkingSpaces: "39",
  },
  {
    city: "Dubai",
    company: "Prime Technologies",
    country: "UAE",
    flag: "🇦🇪",
    name: "Burji Daman (North)",
    ns: "daman-n",
    parkingSpaces: "558",
  },
  {
    city: "Lugano",
    company: "Elecon",
    country: "Switzerland",
    flag: "🇨🇭",
    name: "P.zzo Donini",
    ns: "donini",
    parkingSpaces: "81",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Ehad",
    ns: "ehad",
    parkingSpaces: "83",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Kaplan, 8",
    ns: "gazit",
    parkingSpaces: "50",
  },
  {
    city: "Lugano",
    company: "Elecon",
    country: "Switzerland",
    flag: "🇨🇭",
    name: "Hotel Dante",
    ns: "hdante",
    parkingSpaces: "52",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Herzel",
    ns: "herzel",
    parkingSpaces: "112",
  },
  {
    city: "Auckland",
    company: "Samson",
    country: "New Zealand",
    flag: "🇳🇿",
    name: "Iron Bank",
    ns: "ironbank",
    parkingSpaces: "114",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Kaveri Gold",
    ns: "kg",
    parkingSpaces: "39",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "KG Marg Defence",
    ns: "kgmarg",
    parkingSpaces: "312",
  },
  {
    city: "New Delhi",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Kamla Nagar (Left)",
    ns: "knl",
    parkingSpaces: "912",
  },
  {
    city: "New Delhi",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Kamla Nagar (Right)",
    ns: "knr",
    parkingSpaces: "912",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Krishna Kunj",
    ns: "krishna",
    parkingSpaces: "28",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Matalon",
    ns: "matalon",
    parkingSpaces: "62",
  },
  {
    city: "Menlo Park",
    company: "Parkworks",
    country: "US",
    flag: "🇺🇸",
    name: "Menlo A",
    ns: "menloa",
    parkingSpaces: "248",
  },
  {
    city: "Menlo Park",
    company: "Parkworks",
    country: "US",
    flag: "🇺🇸",
    name: "Menlo B",
    ns: "menlob",
    parkingSpaces: "234",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Mesacon Jewel",
    ns: "mesacon",
    parkingSpaces: "80",
  },
  {
    city: "Miami",
    company: "Park Plus",
    country: "US",
    flag: "🇺🇸",
    name: "The Muse",
    ns: "muse",
    parkingSpaces: "208",
  },
  {
    city: "New Delhi",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "NHIDCL",
    ns: "nhidcl",
    parkingSpaces: "112",
  },
  {
    city: "New Delhi",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Parshvnath",
    ns: "parshvnath",
    parkingSpaces: "218",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Ruth",
    ns: "ruth",
    parkingSpaces: "34",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "SDMC",
    ns: "sdmc",
    parkingSpaces: "406",
  },
  {
    city: "Saint Moritz",
    company: "Elecon",
    country: "Switzerland",
    flag: "🇨🇭",
    name: "Chiesa Carmen",
    ns: "smoritz",
    parkingSpaces: "10",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Teen Murty",
    ns: "teenmurty",
    parkingSpaces: "156",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Trumpeldor",
    ns: "trumpeldor",
    parkingSpaces: "40",
  },
  {
    city: "Mumbai",
    company: "Sotefin Bharat",
    country: "India",
    flag: "🇮🇳",
    name: "Vaibhab Lakshmi",
    ns: "vl",
    parkingSpaces: "56",
  },
  {
    city: "Seattle",
    company: "Parkworks",
    country: "US",
    flag: "🇺🇸",
    name: "Spire",
    ns: "wallstreet",
    parkingSpaces: "276",
  },
  {
    city: "Los Angeles",
    company: "Parkworks",
    country: "US",
    flag: "🇺🇸",
    name: "8888",
    ns: "washingtonblvd",
    parkingSpaces: "213",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Washington Blvd",
    ns: "wblvd",
    parkingSpaces: "33",
  },
  {
    city: "Tel Aviv",
    company: "Parkomat",
    country: "Israel",
    flag: "🇮🇱",
    name: "Wolfson",
    ns: "wolfson",
    parkingSpaces: "62",
  },
];
