export const roles = {
  admin: [
    "dashboard",
    "devices",
    "history",
    "map",
    // "nodes",
    "notifications",
    "operations",
    "rack",
    "racks",
    "tags",
  ],
  service: [
    "dashboard",
    "devices",
    "history",
    "map",
    // "nodes",
    "notifications",
    "operations",
    "rack",
    "racks",
    "tags",
  ],
  valet: ["dashboard", "history", "map", "operations", "tags"],
}
